version: "3.8"
    
services:
  # 1. Entry Point / Load Balancer
  # Constraint: node.role == manager (Berjalan di ripe-ubuntu)
  entry-point:
    image: pratamaze/entry-point:f-grafana # Menggunakan pratamaze/
    ports:
      - "80:8080" # Map port 80 Host ke port 8080 Container
    networks:
      - lb-net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager # Target: ripe-ubuntu (Leader)

  # 2. Backend API Node 1 
  # Constraint: node.hostname == node1.api
  # 2. Backend API Node 1 
  api-node1:
    image: pratamaze/api-service:latest 
    networks:
      - lb-net
    command: ["/apiservice", "-name", "API-NODE-1"] 
    # --- TAMBAHKAN BARIS INI ---
    volumes:
      - /proc:/host/proc:ro # Map /proc host ke /host/proc container (read-only)
    # --------------------------
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == node1.api 

  # 3. Backend API Node 2
  api-node2:
    image: pratamaze/api-service:latest 
    networks:
      - lb-net
    command: ["/apiservice", "-name", "API-NODE-2"]
    # --- TAMBAHKAN BARIS INI ---
    volumes:
      - /proc:/host/proc:ro # Map /proc host ke /host/proc container (read-only)
    # --------------------------
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == node2.api 

          
  # Catatan: api-node3 telah dihapus karena Anda hanya memiliki dua worker node (node1.api, node2.api)
    
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - lb-net
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - lb-net

networks:
  lb-net:
    driver: overlay
    attachable: true
    driver_opts:
      com.docker.network.driver.mtu: "1200" # <-- PENTING: Mengecilkan paket agar muat di Tailscale