version: "3.8"

services:
  # 1. Entry Point / Load Balancer (Jalan di Manager / Node 3)
  entry-point:
    image: pratamaze/loadbalancer:fuzzy-mopso
    environment:
      - LB_ALGO=fuzzy
      - FUZZY_PARAM_SOURCE=optimized
      - MOPSO_BUSINESS_MODE=balanced
      - TRAFFIC_LOG_MODE=window
      - OPTIMIZER_INTERVAL=1s
      - METRICS_INTERVAL=250ms
      - NODE1_CPU_LIMIT_PERCENT=100
      - NODE2_CPU_LIMIT_PERCENT=50
    ports:
      - "80:8080" # Akses publik masuk lewat port 80 VPS Node 3
    networks:
      - lb-net
    volumes:
      - /home/ripe/load-balancer/logs:/logs
      - /home/ripe/load-balancer/storage:/storage
      - /home/ripe/load-balancer/configs:/configs
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager # Otomatis diletakkan di Leader/Manager (Node 3)

  # 2. Backend API Node 1 (Kinerja Penuh 100%)
  api-node1:
    image: pratamaze/nodeapi:fuzzy-mopso
    networks:
      - lb-net
    command: ["/apiservice", "-name", "API-NODE-1"]
    volumes:
      - /proc:/host/proc:ro # Membaca metrik CPU/Load asli dari Host VPS
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          # Pastikan ini sesuai dengan nama hostname VPS Node 1 kamu saat di-cek dengan 'hostname'
          - node.hostname == node1
      resources:
        limits:
          cpus: '1.0' # Menetapkan baseline kapasitas fisik penuh untuk node referensi.

  # 3. Backend API Node 2 (Simulasi Heterogen: Kinerja 50%)
  api-node2:
    image: pratamaze/nodeapi:fuzzy-mopso
    networks:
      - lb-net
    command: ["/apiservice", "-name", "API-NODE-2"]
    volumes:
      - /proc:/host/proc:ro
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == node2
      # --- TAMBAHAN UNTUK RISET HETEROGEN ---
      resources:
        limits:
          cpus: '0.5' # Membatasi container ini hanya boleh pakai 50% core CPU VPS
      # --------------------------------------

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    configs:
      - source: prometheus-config
        target: /etc/prometheus/prometheus.yml
    networks:
      - lb-net
    deploy:
      placement:
        constraints: [node.role == manager]

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - lb-net
    deploy:
      placement:
        constraints: [node.role == manager]
networks:
  lb-net:
    driver: overlay
    attachable: true
    # --- PENTING ---
    # Konfigurasi MTU 1200 untuk Tailscale DIHAPUS.
    # Sekarang Docker menggunakan MTU default agar kecepatan jaringan maksimal.

configs:
  prometheus-config:
    file: ./prometheus.yml
